spring.application.name=CTBS_Demo
############################################
# SERVER CONFIGURATION
############################################
server.port=8080
server.servlet.context-path=/
############################################
# THYMELEAF CONFIGURATION
############################################
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
spring.thymeleaf.encoding=UTF-8
############################################
# STATIC RESOURCES
############################################
spring.web.resources.static-locations=classpath:/static/
############################################
# DATABASE CONFIGURATION (SQL SERVER)
############################################
spring.datasource.url=jdbc:sqlserver://localhost:1433;databaseName=CTBS;encrypt=true;trustServerCertificate=true
spring.datasource.username=sa
spring.datasource.password=1234
spring.datasource.driver-class-name=com.microsoft.sqlserver.jdbc.SQLServerDriver
############################################
# JPA CONFIGURATION
############################################
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.SQLServerDialect
############################################
# JWT CONFIGURATION
############################################
# Kh�a b� m?t ?? k� JWT (Ph?i gi? b� m?t tuy?t ??i, ?�y l� v� d? m� h�a 512-bit)
JWT_TOKEN=DayLaMotKhoaBiMatRatDaiVaPhucTapDungDeMaHoaJwtTokenCuaDuAnCTBSDemo2024!@#
#OAUTH2
spring.security.oauth2.client.registration.google.client-id=${CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
#Gmail
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=khongcogi212@gmail.com
# Thay b?ng m� 16 k� t? b?n v?a l?y ? tr�n
spring.mail.password=xfbi bfzx xxux safq 
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true
############################################
# LOGGING CONFIGURATION
############################################
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE


debug=true

spring.servlet.multipart.max-file-size=500MB
spring.servlet.multipart.max-request-size=505MB